### ISSUE TITLE
Colorpicker not working with python 3.4

### ISSUE THREAD

**Issue by thica** [kivy/kivy#3292]
The colorpicker is not working with python 3.4. If you initalize the widget, an error is raised. It works fine with 2.7

Error in App:Parser: File "C:\dev\Kivy34\kivy34\kivy\data\style.kv", line 1207:
...
   1205:
   1206:            ColorPicker_Selector:
>> 1207:                mroot: root
   1208:                mode: 'hsv'
   1209:                text: 'V'
...
AttributeError: 'bytes' object has no attribute 'format'
  File "C:\dev\Kivy34\kivy34\kivy\lang.py", line 2012, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy\weakproxy.c:1189)
  File "kivy\properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy\properties.c:4680)
  File "kivy\properties.pyx", line 429, in kivy.properties.Property.set (kivy\properties.c:5203)
  File "kivy\properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy\properties.c:5852)
  File "kivy\_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy\_event.c:12154)
  File "kivy\_event.pyx", line 1050, in kivy._event.EventObservers._dispatch (kivy\_event.c:11095)
  File "C:\dev\Kivy34\kivy34\kivy\lang.py", line 1476, in call_fn
    trace('Builder: call_fn => value=%r' % (e_value, ))
  File "kivy\weakproxy.pyx", line 291, in kivy.weakproxy.WeakProxy.__repr__ (kivy\weakproxy.c:8905)

Example App:

```py
import kivy
from kivy.app        import App
from kivy.uix.colorpicker import ColorPicker
        

__version__ = "1.2.0"

class MyApp(App):
    def build(self):
        try:
            self.oColorPicker = ColorPicker()
            return self.oColorPicker
        except Exception as e:
            print ("Error in App:"+str(e))

if __name__ == '__main__':
    MyApp().run()
    
```

**Comment by robertour** [comment]
It is a bug in Kivy 1.9.0. It is working again in the developing version. I would appreciate if there is any work around to fix it in the stable version though. Does anybody knows the commit associated to it?

**Comment by robertour** [comment]
It was fixed in this commit: https://github.com/kivy/kivy/commit/5ee6acd0b83923baf4d4be1d67c9453072c0b6c9

Any ideas of a possible work around for Kivy 1.9.0?

**Comment by dessant** [comment]
Fixed in master.
