### PR TITLE
Resolve the problem of the pygame error: File is not a Windows BMP file

### PR DESCRIPTION
**Pull request by Farkal**
Solution found here -> http://www.akeric.com/blog/?tag=kivy

### CODE REVIEW

**Comment by krusaderjake** [comment]
Hi - I am working with kivy in oracle linux 64-bit and I was receiving the error:

pygame.error: File is not a Windows BMP file

Here is the full error text I receive BEFORE making the change listed in this issue:

'''
[ [1;32mINFO [0m   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[ [1;31mERROR [0m  ] [WinPygame   ] unable to set icon
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/kivy/core/window/window_pygame.py", line 215, in set_icon
    self._set_icon_standard(filename)
  File "/usr/local/lib/python3.4/site-packages/kivy/core/window/window_pygame.py", line 227, in _set_icon_standard
    im = pygame.image.load(filename)
pygame.error: File is not a Windows BMP file
[ [1;33mWARNING [0m] [WinPygame   ] Video: failed (multisamples=2)
[ [1;33mWARNING [0m] [WinPygame   ] trying without antialiasing
[ [1;32mINFO [0m   ] [GL          ] OpenGL version <b'2.1 Mesa 10.4.3'>
[ [1;32mINFO [0m   ] [GL          ] OpenGL vendor <b'Mesa Project'>
[ [1;32mINFO [0m   ] [GL          ] OpenGL renderer <b'Software Rasterizer'>
[ [1;32mINFO [0m   ] [GL          ] OpenGL parsed version: 2, 1
[ [1;32mINFO [0m   ] [GL          ] Shading version <b'1.20'>
[ [1;32mINFO [0m   ] [GL          ] Texture max size <16384>
[ [1;32mINFO [0m   ] [GL          ] Texture max units <32>
[ [1;32mINFO [0m   ] [Window      ] virtual keyboard not allowed, single mode, not docked
'''

**Comment by krusaderjake** [comment]
After I make the change listed in this issue here is the full error text I am receiving:

[ [1;32mINFO [0m   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-01-10_6.txt
[ [1;32mINFO [0m   ] [Kivy        ] v1.9.1
[ [1;32mINFO [0m   ] [Python      ] v3.4.3 (default, Jan  9 2016, 16:11:53) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
[ [1;32mINFO [0m   ] [Factory     ] 179 symbols loaded
[ [1;32mINFO [0m   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
 
 Warning (from warnings module):
   File "/usr/local/lib/python3.4/site-packages/kivy/core/text/text_pygame.py", line 24
     pygame.font.init()
 RuntimeWarning: use font: No module named 'pygame.font'
 (ImportError: No module named 'pygame.font')
[ [1;32mINFO [0m   ] [Text        ] Provider: pil(['text_pygame'] ignored)



*...then at the end of the program:*

[ [1;31mCRITICAL [0m] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/local/lib/python3.4/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.4/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

pygame - TabError: inconsistent use of tabs and spaces in indentation (window_pygame.py, line 203)
  File "/usr/local/lib/python3.4/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

x11 - ImportError: No module named 'kivy.core.window.window_x11'
  File "/usr/local/lib/python3.4/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[ [1;31mCRITICAL [0m] [App         ] Unable to get a Window, abort.

**Comment by krusaderjake** [comment]
##### Please let me know what additional information needed to help resolve this. Thank you.

**Comment by krusaderjake** [comment]
I'm working in python 3.4.3 btw.

**Comment by Farkal** [comment]
I don't know how to fix it for your version of python because i'm using 2.7. But i recommend to use SDL2 instead of pygame, unfortunately i can't use it on centos 7 so i still use pygame.

**Comment by dessant** [comment]
@krusaderjake you've mixed tabs and spaces during the chage and py3 fails in that case.

@Farkal have you tried installing sdl2? It seems there are packages available: https://rpmfind.net/linux/rpm2html/search.php?query=SDL2-devel&submit=Search+...&system=&arch=.
Or you could compile the source.

As for the pr, it strips out Windows ico loading, what is the reason?

**Comment by Farkal** [comment]
Thanks for your answer :smile: 

@dessant yes i have tried, I have also build SDL2 from source but i can't find the source of SDL2-devel and I think that the SDL2-devel on the centos repos is too old. Do you think it's safe to try to install Fedora packages on CentOS 7 ?

For the pr the goal was to remove the error message with windows ico as the author say here -> http://pythonwiki.tiddlyspot.com/#[[Kivy%20%3A%20Debugging%20via%20Wing]]

**Comment by dessant** [comment]
The error does not happen at win ico handling, but in _set_icon_standard, you could handle the exception there.
When i've compiled on debian, using this source seemed to be enough https://www.libsdl.org/release/SDL2-2.0.4.zip, and the rest of the sdl2 deps must be installed too, sdl2_ttf, sdl2_image, sdl2_mixer.
I have no idea about package safety across those distros, I have not used them yet. :-P

**Comment by Farkal** [comment]
Ok but is there a way to remove this error ?
I try to compile fedora packages on centOS and i successfully compile SDL 2.0.4 but it's impossible to compile SDL-devel 2.0.4 (not the same window manager as fedora) so i will wait for the official release.

**Comment by dessant** [comment]
The pygame providers have been deprecated, but if someone provides the right fix for this issue, we can merge it.
