### ISSUE TITLE
Can Not Install Kivy Following Installation Instructions

### ISSUE THREAD

**Issue by COLABORATI** [kivy/kivy#2881]
Following the installation instructions published here:
http://kivy.org/docs/installation/installation-linux.html 

it is not possible to install kivy on my Ubuntu 14.04. 

I am using pyenv [https://github.com/yyuu/pyenv] to get at least some little chance of a sane python environment, so I am following the instructions that are valid for a virtualenv.

First there are two additional libraries that are not mentioned in the installation instructions that should be installed before installing kivy: 
 apt-get install libgstreamer1.0-dev libgles2-mesa-dev

However, I am still not able to install kivy - compilation is stopping with this error:
 
    #error Do not use this file, it is the result of a failed Cython compilation.

see the full error message below.

However, I had no problem installing cython, the cython installation via "pip install cython" finished ok:
       Installing cython script to /home/xxx/.pyenv/versions/2.7.9/bin
       Installing cygdb script to /home/xxx/.pyenv/versions/2.7.9/bin
       Installing cythonize script to /home/xxx/.pyenv/versions/2.7.9/bin
       Successfully installed cython-0.21.2
 
Trying to install Kivy with easy_install also did not work, error messages are quite similar, please see below. 

Also in the FAQ you are writing, regarding errors with pip install: 
    Solution: use easy_install, as our documentation said.

But there is nothing in the documentation saying that easy_install should be used. 

How can I install this stuff? 

   Error compiling Cython file:
    
     ------------------------------------------------------------
    
     ...
    
    
    
                 g_object_set_void(self.playbin, 'video-sink', self.fakesink)
    
    
    
             # configure playbin
    
             g_object_set_int(self.pipeline, 'async-handling', 1)
    
             c_uri = <bytes>self.uri.encode('utf-8')
    
                    ^
    
     ------------------------------------------------------------
    
    
    
     kivy/lib/gstplayer/_gstplayer.pyx:259:16: Storing unsafe C derivative of temporary Python reference
    
    building 'kivy.lib.gstplayer._gstplayer' extension
    
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-pP0Zlq/kivy/kivy/lib
    
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-pP0Zlq/kivy/kivy/lib/gstplayer
    
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/xxx/.pyenv/versions/2.7.9/include/python2.7 -c /tmp/pip-build-pP0Zlq/kivy/kivy/lib/gstplayer/_gstplayer.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-pP0Zlq/kivy/kivy/lib/gstplayer/_gstplayer.o
    
    /tmp/pip-build-pP0Zlq/kivy/kivy/lib/gstplayer/_gstplayer.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
    
     #error Do not use this file, it is the result of a failed Cython compilation.
    
      ^
    
     error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/home/xxx/.pyenv/versions/2.7.9/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-pP0Zlq/kivy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Nneqx1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pP0Zlq/kivy

**Comment by ivlevdenis** [comment]
+

**Comment by ohaz** [comment]
Kivy 1.8 (the current version) is not working with cython 0.21 - please install cython 0.20. We'd like to get 1.9 out soon which is patched

**Comment by COLABORATI** [comment]
Ohaz, it would be really sweet if you would like to copy and paste your answer into the installation instructions and save potentially interested developers a few hours of their precious lifetime! It is very easy and will take just 10 seconds for you to do this, but on the receiving end there will be many hours saved that could be spend with more important things like playing with your children or talking to your mother. 

While developing, when you break anything that is documented in the installation instructions, please immediately change these instructions to reflect these changes - the first-contact-experience is often determining for looking at something ever again or not.

**Comment by ohaz** [comment]
You're right, we should add this to the instructions until 1.9 is released.
