### ISSUE TITLE
Kivy fails to build (kivy/graphics/svg.pyx:469:9)

### ISSUE THREAD

**Issue by thomasdeneux** [kivy/kivy#5606]
I encounter the same problem, or similar, to [issue 5432](https://github.com/kivy/kivy/issues/5432):

`sudo pip3 install kivy`

`kivy/graphics/svg.pyx:469:9: Signature not compatible with previous declaration`

See my complete post in [issue 5432](https://github.com/kivy/kivy/issues/5432). The answer which was given there was to clone a specific branch from the project. I might try to do it, though i don't feel expert enough to compile and install from sources, so I would appreciate if you now have a simpler solution. In any case, i noticed that issue 5432 was closed, but don't consider that it has been solved if anybody with the last releases of cython and kivy encounter the same problem (it appears that i am not the only one). Thank you.

**Comment by KorvinSilver** [comment]
I have the same problem on Arch Linux.

I've tried various combinations of kivy and cython versions but they didn't work:
`kivy 1.10.0` with `cython 0.27.3` -> [full output](https://pastebin.com/p8Ctf6s4)
`kivy 1.10.0` with `cython 0.26.1` -> [full output](https://pastebin.com/3FG2xn1C)
`kivy 1.9.1` with `cython 0.27.3` -> [full output](https://pastebin.com/4VT5bke5)
`kivy 1.9.1` with `cython 0.26.1` -> [full output](https://pastebin.com/zvW3vmgS)
`kivy 1.8.0` with `cython 0.26.1` -> [full output](https://pastebin.com/hHd7MiHQ)
`kivy 1.8.0` with `cython 0.25.2` -> [full output](https://pastebin.com/0aWe2LTk)

I'm not sure what the compatibilities are supposed to be but I can't try every option and I don't want to go further back. Anyway, what does work (at the moment) is this:
`pip install https://github.com/kivy/kivy/archive/master.zip` using `cython 0.27.3`
pip says it's version `1.10.1.dev0`

Note that on Arch Linux the default python is Python 3, currently 3.6.4.

**Comment by bionoid** [comment]
If you look at [setup.py from git tag 1.10.0](https://github.com/kivy/kivy/blob/1.10.0/setup.py#L68-L72) it reports the max supported cython version as 0.25.2. The [setup.py from master](https://github.com/kivy/kivy/blob/master/setup.py#L72-L79) lists 0.27.3.

If you want to run Kivy stable, `pip install Cython==0.25.2`

If you want to run master, `pip install Cython==0.27.3`

**Comment by KorvinSilver** [comment]
Well, it doesn't work with versions 0.23, 0.24 and 0.25.2.  
This is the output where the error occurs:
```
cythoning /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.pyx to /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c
    building 'kivy.core.audio.audio_sdl2' extension
    creating build/temp.linux-x86_64-3.6/tmp/pip-build-obb5wbdp/kivy/kivy/core/audio
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -I/tmp/pip-build-obb5wbdp/kivy/kivy/include -I/usr/local/include/SDL2 -I/usr/include/SDL2 -I/usr/include/SDL2 -I/home/dev/tmp/venv-test/include -I/usr/include/python3.6m -c /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c -o build/temp.linux-x86_64-3.6/tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.o
    /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c: In function ‘__pyx_f_4kivy_4core_5audio_10audio_sdl2_mix_init’:
    /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c:1374:63: error: ‘MIX_INIT_MODPLUG’ undeclared (first use in this function); did you mean ‘MIX_INIT_MOD’?
       __pyx_v_want_flags = (__pyx_v_want_flags | ((MIX_INIT_MOD | MIX_INIT_MODPLUG) | MIX_INIT_FLUIDSYNTH));
                                                                   ^~~~~~~~~~~~~~~~
                                                                   MIX_INIT_MOD
    /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c:1374:63: note: each undeclared identifier is reported only once for each function it appears in
    /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c:1374:83: error: ‘MIX_INIT_FLUIDSYNTH’ undeclared (first use in this function); did you mean ‘MIX_INIT_MID’?
       __pyx_v_want_flags = (__pyx_v_want_flags | ((MIX_INIT_MOD | MIX_INIT_MODPLUG) | MIX_INIT_FLUIDSYNTH));
                                                                                       ^~~~~~~~~~~~~~~~~~~
                                                                                       MIX_INIT_MID
    /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c: In function ‘__pyx_pf_4kivy_4core_5audio_10audio_sdl2_9MusicSDL2_extensions’:
    /tmp/pip-build-obb5wbdp/kivy/kivy/core/audio/audio_sdl2.c:4527:69: error: ‘MIX_INIT_MODPLUG’ undeclared (first use in this function); did you mean ‘MIX_INIT_MOD’?
       __pyx_t_2 = ((__pyx_v_4kivy_4core_5audio_10audio_sdl2_mix_flags & MIX_INIT_MODPLUG) != 0);
                                                                         ^~~~~~~~~~~~~~~~
                                                                         MIX_INIT_MOD
     error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/dev/tmp/venv-test/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-obb5wbdp/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ythgjcqs-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dev/tmp/venv-test/include/site/python3.6/kivy" failed with error code 1 in /tmp/pip-build-obb5wbdp/kivy/
```
The only difference is where they indicate the row and column numbers of `audio_sdl2.c`.

And with version 0.25 I get this:
```
warning: manifest_maker: standard file '-c' not found
    
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-n8eqxlq7/kivy/setup.py", line 1060, in <module>
         ] if not skip_cython else [])
       File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
         dist.run_commands()
       File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
         self.run_command(cmd)
       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
         cmd_obj.run()
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 279, in run
         self.find_sources()
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
         mm.run()
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 533, in run
         self.add_defaults()
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
         sdist.add_defaults(self)
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
         self._add_defaults_ext()
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
         build_ext = self.get_finalized_command('build_ext')
       File "/usr/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
         cmd_obj.ensure_finalized()
       File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
         self.finalize_options()
       File "/tmp/pip-build-n8eqxlq7/kivy/setup.py", line 251, in finalize_options
         retval = build_ext.finalize_options(self)
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/Cython/Distutils/build_ext.py", line 19, in finalize_options
         self.distribution.ext_modules)
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 809, in cythonize
         aliases=aliases)
       File "/home/dev/tmp/venv-test/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 752, in create_extension_list
         **kwds))
       File "/tmp/pip-build-n8eqxlq7/kivy/setup.py", line 511, in __init__
         self.sources = args[1]
     IndexError: tuple index out of range
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n8eqxlq7/kivy/
```

**Comment by bionoid** [comment]
@KorvinSilver the error with 0.25.3 is different, your version of SDL2 Mixer is too new. Either downgrade sdl2-mixer or use kivy master branch which contains a fix.

**Comment by thomasdeneux** [comment]
Thanks to the both of you. The two following approaches worked:

- `pip install https://github.com/kivy/kivy/archive/master.zip` using the latest version of Cython (0.27.3)

- `pip install Cython==0.25.2` followed by `pip install kivy`

So I kept the result of the second install. I understand that i should have read the `setup.py` file on Github to know which version of Cython to use, but shouldn't pip itself figure out by reading the file that he should temporarily install the specified version of Cython?

**Comment by KorvinSilver** [comment]
@bionoid Then master branch it is.

**Comment by lszyba1** [comment]
Is there an eta for a fix for pip install kivy
for Debian Stable.
Currently the workaround is : 
https://github.com/kivy/kivy/issues/5432#issuecomment-377741748

**Comment by stroobandt** [comment]
I `RAN` into the same issue with `kivy v1.10.1` and `Cython version 0.28.2`:

```
  RAN: /usr/local/bin/cython ./kivy/graphics/svg.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
                end = time()
                Logger.debug("Svg: Loaded {} in {:.2f}s".format(filename, end - start))
            finally:
                fd.close()

    cdef void reload(self) except *:
        ^
------------------------------------------------------------

kivy/graphics/svg.pyx:469:9: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
        cpdef flag_update(self, int do_parent=?, list _instrs=?)
    ELSE:
        cpdef flag_update(self, int do_parent=?)
    cdef void flag_update_done(self)
    cdef void set_parent(self, Instruction parent)
    cdef void reload(self)
                   ^
------------------------------------------------------------

kivy/graphics/instructions.pxd:36:20: Previous declaration is here
```

**Comment by tito** [comment]
This issue was fixed, and is inherent with every newer Cython version. We fix it as soon as a new Cython version is out;
The SVG issue is fixed already in master.
