### ISSUE TITLE
Installation Failure on OSX High Sierra (Logs Attached)

### ISSUE THREAD

**Issue by razed11** [kivy/kivy#5644]
### Versions

* Python: 3.4
* OS: 10.13.3
* Kivy: 1.10.0
* Kivy installation method: [Homebrew](https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip)
### Description

I'm getting errors when trying to install Kivy.  I've read through a couple of similar issues but none of the suggestions were helpful. I have tried several versions of Cython including that which is suggested. I get errors with `pip install kivy`. The previous steps are fine.

Output of stdout and stderr is attached but this error seems suspicious:

```
 # error SDL for Mac OS X only supports deploying on 10.6 and above.
```

And an undefined:

```
audio_sdl2.c:1647:63: error: use of undeclared identifier 'MIX_INIT_MODPLUG'; did you mean 'MIX_INIT_MOD'?
      __pyx_v_want_flags = (__pyx_v_want_flags | ((MIX_INIT_MOD | MIX_INIT_MODPLUG) | MIX_INIT_FLUIDSYNTH));
```

[kivy.install.errors.txt](https://github.com/kivy/kivy/files/1791084/kivy.install.errors.txt)

**Comment by bionoid** [comment]
The audio_sdl2 error is due to a breaking upstream change in SDL2-mixer; a fix has been merged in Kivy master branch, but no new stable release has been made since then. Either install Kivy master branch or downgrade sdl2-mixer.

I'm not sure if the other error is caused by this or not

**Comment by razed11** [comment]
I tried a build with a Python 3.6 and eliminated the OSX version error but yes the audio error remains.

@bionoid Is it possible to build without `sdl2-mixer`? I don't think I need that. But I can also try a downgrade. I only hope that there aren't dependencies somehow that will be disturbed by that downgrade.

**Comment by razed11** [comment]
`brew uninstall sdl2_mixer` followed by `pip install kivy` seems to have worked.

Not sure why the configuration is old. This is the first time I have install Kivy.

```
Successfully built kivy
Installing collected packages: kivy
Successfully installed kivy-1.10.0
Silverback: python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy
[WARNING] [Config      ] Older configuration version detected (0 instead of 19)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /Users/Kenny/.kivy/logs/kivy_18-03-08_0.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

**Comment by bionoid** [comment]
I am slightly surprised it compiled without sdl2-mixer, but okay, good! ;) I guess you just ended up missing audio support via sdl2 (normally not used on desktop platforms anyway). I guess there is native coreaudio support on macos (but don't quote me on that), so probably you won't notice this.. but don't quote me on that either. I don't know about homebrew, but if you can specify version, sdl2-mixer 2.0.1 should do the trick, or reinstall 2.0.2 and do `pip install kivy==master` instead

> Not sure why the configuration is old.

Ignore that, it's just because no configuration existed (counts as version 0, which is old..)

**Comment by razed11** [comment]
Thanks a bunch.

FYI: `pip install kivy==master` did not work for me. I was able to install the latest `sdl2_mixer` and then:

`pip install git+https://github.com/kivy/kivy@master` to pick up 10.1.1.dev0. Also resolved #5681.
