### PR TITLE
Fix an inconsistency between docs and code on Camera

### PR DESCRIPTION
**Pull request by misl6**
This PR fixes an inconsistency between docs and code.

The issue was been introduced by PR #658

### CODE REVIEW

**Comment by Cheaterman** [comment]
This crashes with CameraGi:

```
   File "/home/cheaterman/Dev/Kivy/kivy/core/camera/camera_gi.py", line 137, in _update
     self.dispatch('on_load')
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "/home/cheaterman/Dev/Kivy/kivy/uix/camera.py", line 112, in _camera_loaded
     self.texture_size = list(self.texture.size)
 AttributeError: 'NoneType' object has no attribute 'size'
```

See #7049.
