### ISSUE TITLE
Fails to build with clang 17 and GCC 14 due to -Wincompatible-pointer-types

### ISSUE THREAD

**Issue by kanavin** [kivy/kivy#8557]
When building 2.3.0 with clang, the following error occurs:
```
/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/python3-kivy/2.3.0/git/kivy/graphics/cgl_backend/cgl_gl.c:4549:52: error: incompatible function pointer types assigning to 'void (*)(GLuint, GLsizei, const GLchar **, const GLint *)' (aka 'void (*)(unsigned int, int, const char **, const int *)') from 'void (GLuint, GLsizei, const GLchar *const *, const GLint *)' (aka 'void (unsigned int, int, const char *const *, const int *)') [-Wincompatible-function-pointer-types]
 4549 |   __pyx_v_4kivy_8graphics_3cgl_cgl->glShaderSource = glShaderSource;
      |                                                    ^ ~~~~~~~~~~~~~~
```

Full build log:
https://sprunge.us/lq5PKS

**Comment by misl6** [comment]
Hi @kanavin ,

This one could be related: https://github.com/kivy/kivy/pull/8415


Can you please confirm your clang version?

**Comment by kanavin** [comment]
> Hi @kanavin ,
> 
> This one could be related: #8415
> 
> Can you please confirm your clang version?

@kraj I think this was this with 17.x?

**Comment by kraj** [comment]
> > Hi @kanavin ,
> > This one could be related: #8415
> > Can you please confirm your clang version?
> 
> @kraj I think this was this with 17.x?

yes, 17.0.6 to be precise

**Comment by misl6** [comment]
As pointed out by @glaubitz in #8746 , the same issue is happening on GCC 14. (Issue title updated)

**Comment by glaubitz** [comment]
I just tried to have a go at this and tried the following change:

```diff
diff -Nru kivy-2.3.0.orig/kivy/core/window/_window_sdl2.pyx kivy-2.3.0/kivy/core/window/_window_sdl2.pyx
--- kivy-2.3.0.orig/kivy/core/window/_window_sdl2.pyx   2024-01-05 10:40:12.000000000 +0100
+++ kivy-2.3.0/kivy/core/window/_window_sdl2.pyx        2024-06-11 09:59:18.605347161 +0200
@@ -263,7 +263,7 @@
         for joy_i in range(SDL_NumJoysticks()):
             SDL_JoystickOpen(joy_i)
 
-        SDL_SetEventFilter(<SDL_EventFilter *>_event_filter, <void *>self)
+        SDL_SetEventFilter(<SDL_EventFilter>_event_filter, <void *>self)
 
         SDL_EventState(SDL_DROPFILE, SDL_ENABLE)
         SDL_EventState(SDL_DROPTEXT, SDL_ENABLE)
```

But that doesn't work, but I am also not very familiar with Cython. Could someone with Cython expertise please have a look at this?

The kivy package is otherwise on the risk of being removed from distributions if it doesn't build with GCC 14.

**Comment by glaubitz** [comment]
Any news on this?

**Comment by duelafn** [comment]
I think the fix in #8415 is/was incorrect. The author points to the [GL4 documentation](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glShaderSource.xhtml), which indeed shows the function definition,

``` C
void glShaderSource(
    GLuint shader,
    GLsizei count,
    const GLchar **string,
    const GLint *length
);
```

However, the kivy source file comment links to the [ES2 documentation](https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glShaderSource.xml) which has function definition,

``` C
void glShaderSource(
    GLuint shader,
    GLsizei count,
    const GLchar * const *string,
    const GLint *length
);
```

Since kivy seems to `include GLES2/gl2.h`, I believe that (part of) the correct
response for the current issue is to revert a0ec8ff79fcbc1b82391132a89c8fc21ef1c5c55.

In the Debian build, this fixes the `-Wincompatible-pointer-types` error in

```
 4562 |   __pyx_v_4kivy_8graphics_3cgl_cgl->glShaderSource = glShaderSource;
```


This leaves

``` python
    # kivy/core/window/_window_sdl2.pyx line 266
    SDL_SetEventFilter(<SDL_EventFilter *>_event_filter, <void *>self)
```

Which produces error,

```
 8756 |   SDL_SetEventFilter(((SDL_EventFilter *)(&__pyx_f_4kivy_4core_6window_12_window_sdl2__event_filter)), ((void *)__pyx_v_self));
      |                      ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       |
      |                       int (**)(void *, SDL_Event *)
In file included from /usr/include/SDL2/SDL.h:41,
                 from /build/kivy-2.3.0/kivy/core/window/_window_sdl2.c:1302:
/usr/include/SDL2/SDL_events.h:1017:65: note: expected 'SDL_EventFilter' {aka 'int (*)(void *, SDL_Event *)'} but argument is of type 'int (**)(void *, SDL_Event *)'
 1017 | extern DECLSPEC void SDLCALL SDL_SetEventFilter(SDL_EventFilter filter,
      |                                                 ~~~~~~~~~~~~~~~~^~~~~~
```

Which I'm not sure how to fix.

Additional testing may be needed to determine whether #8415 can be replicated.

**Comment by duelafn** [comment]
Sorry, I missed that kivy can compile using either GLES or GL, so it appears as though the glShaderSource definitions need to conditionally choose between `const GLchar**` and `const GLchar* const*` depending on the `__USE_OPENGL_ES2` flag.

**Comment by danfe** [comment]
I've stumbled upon this issue as well when building under FreeBSD with Clang which also treats incompatible pointer types as errors, and had to modify some source files like this:
```shell
sed -i.orig -e '/GLSHADERSOURCEPTR/s,const GLchar\*,& const ,' \
    kivy/graphics/cgl.pxd
sed -i.orig -e '/glShaderSource/s,const GLchar\*,& const ,' \
    kivy/graphics/cgl.pxd \
    kivy/graphics/cgl_backend/cgl_gl.pyx \
    kivy/include/common_subset.h
sed -i.orig -e '/mockShaderSource/s,const GLchar\*,& const,' \
    kivy/graphics/cgl_backend/cgl_mock.pyx
sed -i.orig -e '/dbgShaderSource/s,const GLchar\*,& const,' \
    kivy/graphics/cgl_backend/cgl_debug.pyx
```
Now that I've read about GLES vs GL difference in the previous comment, I'll give it another look and try to come up with a better, more complete patch.

**Comment by cederom** [comment]
I can see that above problem was probably fixed in the kivy master but now I have different build problem to build master ;-)

```
building 'kivy.graphics.cgl_backend.cgl_gl' extension
cc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/XXX/kivy.git/kivy/include -I/usr/local/include -I/XXX/kivy.git/kivy/include -I/XXX/venv/include -I/usr/local/include/python3.11 -c /XXX/kivy.git/kivy/graphics/cgl_backend/cgl_gl.c -o build/temp.freebsd-13.3-RELEASE-p7-amd64-cpython-311/XXX/kivy.git/kivy/graphics/cgl_backend/cgl_gl.o
/XXX/kivy.git/kivy/graphics/cgl_backend/cgl_gl.c:3535:52: error: incompatible function pointer types assigning to 'void (*)(GLuint, GLsizei, const GLchar **, const GLint *)' (aka 'void (*)(unsigned int, int, const char **, const int *)') from 'void (GLuint, GLsizei, const GLchar *const *, const GLint *)' (aka 'void (unsigned int, int, const char *const *, const int *)') [-Wincompatible-function-pointer-types]
 3535 |   __pyx_v_4kivy_8graphics_3cgl_cgl->glShaderSource = glShaderSource;
      |                                                    ^ ~~~~~~~~~~~~~~
1 error generated.

% uname -a
FreeBSD octagon 13.3-RELEASE-p7 FreeBSD 13.3-RELEASE-p7 GENERIC amd64

% cc --version
FreeBSD clang version 17.0.6 (https://github.com/llvm/llvm-project.git llvmorg-17.0.6-0-g6009708b4367)
Target: x86_64-unknown-freebsd13.3
Thread model: posix
InstalledDir: /usr/bin

% python3 --version
Python 3.11.10
```
```

**Comment by cederom** [comment]
* Okay I can confirm that @danfe fix works for both Kivy 2.3.0 and 3.0.0-dev0 (git master).
* API seems to have changed in master and my application that works with 2.3.0 does not work with 3.0.0-dev0 (git master).
* PR for testing / verification is here: https://github.com/kivy/kivy/pull/8911
* Would it be possible to release Kivy 2.3.1 patch release with this fix please?

**Comment by cederom** [comment]
> @misl6: Hi @kanavin ,
> This one could be related: #8415
> Can you please confirm your clang version?

Yes this is the cause of the problem.

**Comment by cederom** [comment]
Additional info fixing Kivy 2.3.0 build also enables KivyMD 1.1.1 install with no problem. This is a serious blocker I was supposed to make the app release today :-(

**Comment by duelafn** [comment]
@cederom Correct, #8792 is only a partial fix. In Debian we also applied a patch reverting a0ec8ff. From what I can tell, a0ec8ff is required when compiling against GL, but a0ec8ff must be removed when compiling against GLES. Unfortunately I don't know enough about cython to make the settings configurable or whether some kind of shim would be required so that the cython could be the same for both libraries.

**Comment by danfe** [comment]
> @danfe do you think creating KivyMD (1.1.1) port / package would be possible? Do not use 1.2.0 nor 2.0.0 they are still unusable :-)

It certainly looks possible, I'll see what I can do.

**Comment by misl6** [comment]
#8911 has been merged and #8917 (backport for 2.3.x) is completing CI/CD steps and will be merged as soon we have green checkmarks.

Explained [here](https://github.com/kivy/kivy/pull/8911#issuecomment-2466262722) why #8911 has been accepted.

**Comment by misl6** [comment]
Closing as fixed (both #8792 and #8911 have been merged).
Feel free to open a new issue if the issue persists.

Thank you to everyone who contributed with both tests and code!

**Comment by cederom** [comment]
Thank you @misl6 for quick reaction :-)

Quick build check on FreeBSD, clang 17.0.6, cython 0.29.30, Python 3.9.20:
* git master fails.
* 2.3.0 fails (cython too low).

Quck build check on FreeBSD, clang 17.0.6, cython 0.29.37 (latest 0.29), Python 3.9.20:
* git master ok.
* 2.3.0 fails.
* git devel-2.3.x ok.

Quick build check on FreeBSD, clang 17.0.6, cython 3.0.11, Python 3.11.10 (all latest stuff):
* git master ok.
* 2.3.0 fails.
* git devel-2.3.x ok.

Summary:
* Problem still persist on kivy release / tag 2.3.0 clang 17. It is not possible to install Kivy with pip. Manual build and install from git devel-2.3.x is necessary.
* I can see that devel-2.3.x branch already contains the fixes, tested, builds and works fine :-)
* Would it be possible to create Kivy 2.3.1 patch release? It will be then possible to install Kivy 2.3.1 with pip :-) Release notes may contain information about GCC 14 and CLANG 17 fixes and are confirmed to build with clang 17.0.6, cython 3.0.11, Python 3.11.10.

**Comment by misl6** [comment]
> Would it be possible to create Kivy 2.3.1 patch release? It will be then possible to install Kivy 2.3.1 with pip :-) Release notes may contain information about GCC 14 and CLANG 17 fixes and are confirmed to build with clang 17.0.6, cython 3.0.11, Python 3.11.10.

Kivy 2.3.1 is scheduled, and we will have a release as soon the CI/CD pipeline is all green on `devel-2.3.x` branch.
