### ISSUE TITLE
[CRITICAL] [Window      ] Unable to find any valuable Window provider.

### ISSUE THREAD

**Issue by anshulvj** [kivy/kivy#5862]
I installed Kivy following instructions given [here](https://kivy.org/docs/installation/installation-linux.html) on my Ubuntu 16.04 64-bit system. I am working with Python3.6

I ran the following script from their documentation:

```
import kivy
kivy.require('1.0.6') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()
```

**Error**:
```
[WARNING] [Config      ] Older configuration version detected (19 instead of 20)
WARNING:kivy:[Config      ] Older configuration version detected (19 instead of 20)
[WARNING] [Config      ] Upgrading configuration in progress.
WARNING:kivy:[Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/anshulvj/.kivy/logs/kivy_18-07-16_45.txt
INFO:kivy:[Logger      ] Record log in /home/anshulvj/.kivy/logs/kivy_18-07-16_45.txt
[INFO   ] [Kivy        ] v1.10.1
INFO:kivy:[Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.6 (default, Jun 28 2018, 04:42:43) 
[GCC 5.4.0 20160609]
INFO:kivy:[Python      ] v3.6.6 (default, Jun 28 2018, 04:42:43) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 194 symbols loaded
INFO:kivy:[Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_pygame, img_ffpyplayer ignored)
INFO:kivy:[Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_pygame, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_pygame'] ignored)
INFO:kivy:[Text        ] Provider: pil(['text_pygame'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

pygame - ModuleNotFoundError: No module named 'pygame'
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/window/window_pygame.py", line 8, in <module>
    import pygame

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

CRITICAL:kivy:[Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

pygame - ModuleNotFoundError: No module named 'pygame'
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/window/window_pygame.py", line 8, in <module>
    import pygame

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/anshulvj/IRS2-415-Python/venv/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
CRITICAL:kivy:[App         ] Unable to get a Window, abort.

Process finished with exit code 1

```

When I followed instructions given in the section **Using software packages**, the script was failing in Python3.6 but working fine in Python3.6 (using command line Python without virtual environment).

When I followed instructions given in section **Installation in a Virtual Environment**, the script fails in virtual environments irrespective of whether they use Python 3.5 or 3.6 with the error given above.

My guess is some dependencies are not installed properly even though I followed the instructions given on the link above without any issues. 

Any pointers are appreciated.

**Comment by matham** [comment]
Which version of kivy are you using? Did you install the deps listed here: https://kivy.org/docs/installation/installation-linux.html#ubuntu-example ? It seems like you don't have the SDL2 deps installed. Try with those deps installed and compile kivy again.

**Comment by matham** [comment]
I would not recommend that you use pygame for our window manager as although it probably works, our recommended window manager is sdl2. That is what is commonly used.
