### ISSUE TITLE
Kivy won't build with Cython 0.26

### ISSUE THREAD

**Issue by inclement** [kivy/kivy#5327]
Trying to build gives an error like the following:

```
  RAN: '/usr/bin/cython ./kivy/lib/vidcore_lite/egl.pyx'

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_DISPLAY_HANDLE_T disp
        bcm.DisplayHandle D
    disp = bcm.vc_dispmanx_display_open( device )
    if disp == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to display")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:608:17: cimported module has no attribute 'BCMDisplayException'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_UPDATE_HANDLE_T hdl
        bcm.UpdateHandle U
    hdl = bcm.vc_dispmanx_update_start( priority )
    if hdl == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to update-start")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribute 'BCMDisplayException'


  STDERR:

```

**Comment by inclement** [comment]
I think this doesn't affect most builds because it only happens if vidcore_lite is cythonised. It does affect android builds, since everything is cythonised automatically.

**Comment by KeyWeeUsr** [comment]
What about version `0.25.2`?

Also, try to add `cdef` on [this line](https://github.com/kivy/kivy/blob/4bd65154e2d52b3f9ca71d8fbf59a77d1620d41a/kivy/lib/vidcore_lite/bcm.pyx#L57) and/or `import bcm` after [this line](https://github.com/kivy/kivy/blob/4bd65154e2d52b3f9ca71d8fbf59a77d1620d41a/kivy/lib/vidcore_lite/egl.pyx#L4) because it seems like a really strange "error".

**Comment by inclement** [comment]
I've already made a PR with the latter solution, which seems to work.

**Comment by 11USERNAME11** [comment]
So, how to fix this error?

**Comment by KeyWeeUsr** [comment]
@11USERNAME11 It should be already fixed in the master branch.

**Comment by OptimusGREEN** [comment]
downgrading python to 0.25 solved this for me.

`pip install 'cython == 0.25'`

**Comment by KeyWeeUsr** [comment]
@OptimusGREEN didn't master with cython version at least `0.25.3` work?

**Comment by OptimusGREEN** [comment]
I didn't install from master, figured I'd stick with release and just downgrade python. still learning :)

**Comment by lostc4t** [comment]
working: kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribute 'BCMDisplayException'

even after downgrading cython: pip install Cython==0.25

I'm trying this on OSX though...

**Comment by KeyWeeUsr** [comment]
@vaab

This is for stable (currently `1.10.0`):
https://github.com/kivy/kivy/blob/a4116a58d7c5448a4c6615021302375cbe3e129a/setup.py#L70

This is for master branch (latest stuff, `pip install https://github.com/kivy/kivy/zipball/master`):
https://github.com/kivy/kivy/blob/00c161d076fc754357a133e483699146cdd81518/setup.py#L74

Documentation at kivy.org is built from master branch, therefore every version mentioned is most likely meant **mainly** for the **master** branch. If you combine `stable` and deps for `master` or vice-versa you are going for troubles. Parts such as [this](https://kivy.org/docs/installation/installation-linux.html#cython) may get outdated often-ishly if there's a change in the code that requires using the newer version and e.g. a feature A wouldn't be possible in older Cython versions. We welcome any reports related to this as such changes make Kivy not working.

From this I conclude that either you do the bad combination with branch and wrong deps version(s), or the wrong variable is actually `MIN_CYTHON_STRING` in the `master` branch (feel free to open a separate issue or PR fixing it). If I'm wrong, please correct me.

**Comment by veluvj** [comment]
i had the same issues but after updating cython build successfully.

`pip install 'cython == 0.25'
`
