### ISSUE TITLE
Crash when pasting a file into a text input widget in master (Kivy 1.9-dev)

### ISSUE THREAD

**Issue by arafangion** [kivy/kivy#2877]
The crash occurs on line 27 in get, with the latest kivy master built against SDL2:

Line 27, of kivy/core/clipboard/clipboard_winctypes.py, in get:

AttributeErrror: 'NoneType' object has no attribute 'encode'.

How to reproduce:
On windows (this is windows specific):
1) Select a file using windows explorer. Copy it by pressing control-C.
2) Paste it into a text input widget, this results in the 'c_wchar_p(pcontents).value' being None, so calling .encode on it won't make sense.

This works in Kivy 1.8, because that version does not perform the .encode call.

The fix is to do something like:

data = c_wchar_p(pcontents).value
if isinstance(data, unicode):
    data = data.encode('utf-16')

**Comment by arafangion** [comment]
Should now be fixed by https://github.com/kivy/kivy/commit/7fba848a2ceb6c5494c98ddea57dc8f8a78be913
