### ISSUE TITLE
White square when loading zip Image on Windows (1.9.0-dev)

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2823]
Zip loading works in 1.8.0, must be related to #1730.
On a side note #2102 might also be related, although it's likely buggy in both versions. Needs confirmation, but it all comes down to reloading and refreshing of zipped images. I think some code must be written to trigger the update when the source isn't a static file but a collection.

EDIT. A zip file: https://drive.google.com/open?id=0B3-RtQdBRQiOMHJ4SFRodVZWNE0&authuser=0

**Comment by tshirtman** [comment]
can you run the example?
```
python examples/widgets/sequenced_images/main.py
```
seems to work for me (linux)

**Comment by victor-rene** [comment]
Running "python examples/widgets/sequenced_images/main.py". The fifth widget on the left bar is a white square on Windows (1.9.0-dev).

**Comment by tshirtman** [comment]
actually works for me after `make force` on master, may be the result of a faulty compilation.

**Comment by bionoid** [comment]
It seems like my system has the same problem as @victor-rene for sequenced_images example - fifth widget is white.

"Load gif" button works; both "zipped png's" and "zipped jpg's" produce a white square only. The remaining 4 buttons all crash the app with this:

```
     _animdelay = self.img._coreimage.anim_delay
 AttributeError: 'NoneType' object has no attribute 'anim_delay'
```

**Comment by victor-rene** [comment]
@bionoid I wrote about the _coreimage problem yesterday in IRC, it fell into dead ears. I don't know if opening another issue is the right thing to do, but a user of AsyncImage was searching for a way to bypass caching (finally solved with setting nocache=True). Meanwhile I suggested self.img._coreimage.remove_from_cache() which caused the same error message AttributeError: 'NoneType' object has no attribute 'remove_from_cache'. I feel like something is going on here.

**Comment by akshayaurora** [comment]
@victor-rene you have http://kivy.org/docs/api-kivy.uix.image.html#kivy.uix.image.Image.nocache and http://kivy.org/docs/api-kivy.uix.image.html#kivy.uix.image.Image.reload both mentioned in the docs, the issue with .zip is not reproducible for me on windows 8.1 with the latest master.

As tshirtman outlined doing `make force` to make sure you have everything compiled for master does not reproduce the issue. On irc you simply didn't respond the question when I asked whether you had done `make force`. Please give us more details on whether this is working with make force and which version of windows are you using.

**Comment by victor-rene** [comment]
@akshayaurora It's quite possible I missed your question, sorry for that. OS is Windows 7 Home 64-bit, I always use "make force", I only learned about "make" yesterday. I will certainly retry it again today, but bionoid already confirmed it.

On a side note, nocache and reload are mentioned, but it has nothing to do with why _coreimage is None, in some of the issues. If you could enlighten me on this I would appreciate.

**Comment by victor-rene** [comment]
On Ubuntu mini 14.10. Running python examples/widgets/sequenced_images/main.py
 - latest kivy master (git clone yesterday, fetch just now)
 - make force
White square & crash (the same thing as Windows OS).

[INFO              ] Logger: Record log in /home/victor/.kivy/logs/kivy_15-01-05_9.txt
[INFO              ] Kivy v1.9.0-dev
[INFO              ] Python: v2.7.8 (default, Oct 20 2014, 15:05:29) 
[GCC 4.9.1]
[INFO              ] Factory: 173 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer, img_sdl2 ignored)
[INFO              ] Text: Provider: pygame
[INFO              ] Window: Provider: pygame(['window_egl_rpi'] ignored)
[WARNING           ] WinPygame: Video: failed (multisamples=2)
[WARNING           ] WinPygame: trying without antialiasing
[INFO              ] GL: OpenGL version <2.1 Chromium 1.9>
[INFO              ] GL: OpenGL vendor <Humper>
[INFO              ] GL: OpenGL renderer <Chromium>
[INFO              ] GL: OpenGL parsed version: 2, 1
[INFO              ] GL: Shading version <4.40 NVIDIA via Cg compiler>
[INFO              ] GL: Texture max size <16384>
[INFO              ] GL: Texture max units <32>
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] Base: Start application main loop
[INFO              ] GL: NPOT texture support is available
[INFO              ] Base: Leaving application in progress...
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "examples/widgets/sequenced_images/main.py", line 147, in <module>
[WARNING           ] stderr:     mainApp().run()
[WARNING           ] stderr:   File "/home/victor/kivy/kivy/app.py", line 825, in run
[WARNING           ] stderr:     runTouchApp()
[WARNING           ] stderr:   File "/home/victor/kivy/kivy/base.py", line 484, in runTouchApp
[WARNING           ] stderr:     EventLoop.window.mainloop()
[WARNING           ] stderr:   File "/home/victor/kivy/kivy/core/window/window_pygame.py", line 381, in mainloop
[WARNING           ] stderr:     self._mainloop()
[WARNING           ] stderr:   File "/home/victor/kivy/kivy/core/window/window_pygame.py", line 285, in _mainloop
[WARNING           ] stderr:     EventLoop.idle()
[WARNING           ] stderr:   File "/home/victor/kivy/kivy/base.py", line 327, in idle
[WARNING           ] stderr:     self.dispatch_input()
[WARNING           ] stderr:   File "/home/victor/kivy/kivy/base.py", line 312, in dispatch_input
[WARNING           ] stderr:     post_dispatch_input(*pop(0))
[WARNING           ] stderr:   File "/home/victor/kivy/kivy/base.py", line 278, in post_dispatch_input
[WARNING           ] stderr:     wid.dispatch('on_touch_up', me)
[WARNING           ] stderr:   File "_event.pyx", line 701, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6829)
[WARNING           ] stderr:   File "/home/victor/kivy/examples/widgets/sequenced_images/uix/custom_button.py", line 88, in on_touch_up
[WARNING           ] stderr:     _animdelay = self.img._coreimage.anim_delay
[WARNING           ] stderr: AttributeError: 'NoneType' object has no attribute 'anim_delay'

**Comment by kived** [comment]
The example works for me (Ubuntu 14.10) with img_pil, but produces the above behavior with img_pygame and img_sdl2.

**Comment by victor-rene** [comment]
After bisecting, commit 1ffcb9f7a16ddf7438b5af1f9bd0bd477d0029cb is the culprit (change image pygmae to use file handles instead of path because of unicode issues).

**Comment by victor-rene** [comment]
UPDATE:
On current master, at https://github.com/kivy/kivy/blob/master/kivy/core/image/__init__.py#L339
ImageLoaderPygame genererate an exception upon trying to load the tmpfile from SIO.BytesIO(z.read(zfilename))

**Comment by akshayaurora** [comment]
@victor-rene does changing https://github.com/kivy/kivy/blob/master/kivy/core/image/__init__.py#L54-L57 to import io as SIO solve the issue you are having?

**Comment by victor-rene** [comment]
@akshayaurora Changing cio as SIO to io as SIO doesn't help.

UPDATE 3: I don't understand what's going on. The method call silently fails without an Exception. I verified the types of the objects: 

at ImageLoaderBase: https://github.com/kivy/kivy/blob/master/kivy/core/image/__init__.py#L200
<kivy.core.image.img_pygame.ImageLoaderPygame object at 0x05F9C170> <_io.BytesIO object at 0x05FA4540>
<bound method ImageLoaderPygame.load of <kivy.core.image.img_pygame.ImageLoaderPygame object at 0x05F9C170>>

I see no reason why a bound method, with it's live instance would failed to get called without raising.

**Comment by victor-rene** [comment]
UPDATE 6: Full stack trace. traceback.format_exc()

    Traceback (most recent call last):
      File "C:\dev\program\Kivy-1.9.0-dev\kivy\kivy\core\image\__init__.py", line 340, in zip_loader
        im = loader(tmpfile, **kwargs)
      File "C:\dev\program\Kivy-1.9.0-dev\kivy\kivy\core\image\__init__.py", line 200, in __init__
        self._data = self.load(filename)
      File "C:\dev\program\Kivy-1.9.0-dev\kivy\kivy\core\image\img_pygame.py", line 52, in load
        elif isfile(filename):
      File "C:\dev\program\Kivy-1.9.0-dev\Python27\lib\genericpath.py", line 29, in isfile
        st = os.stat(path)
    TypeError: coercing to Unicode: need string or buffer, _io.BytesIO found

**Comment by victor-rene** [comment]
UPDATE 7: FIXED. It seems you have to account for how os.path.isfile() is implemented by casting the buffer to str. Solution. https://github.com/kivy/kivy/blob/master/kivy/core/image/img_pygame.py#L50-52

    elif isfile(str(filename)):
        with open(filename, 'rb') as fd:
            im = pygame.image.load(fd)

I follow with a PR and probably close. Report in PR comment if it's not the right fix.

**Comment by kived** [comment]
Still an issue with animated gifs, though #2834 fixes zip animations. Also an issue on SDL2.

**Comment by victor-rene** [comment]
UPDATE 8. This line https://github.com/kivy/kivy/blob/master/kivy/core/image/_img_sdl2.pyx#L43
for SDL2.

**Comment by matham** [comment]
Putting `str` is definately wrong. In py2, it's convert it to `bytes`, but what if the filename is unicode. The opposite problem occurs in py3. The real problem is not with the filename, it's because we're missing a che3ck whether it's a BytesIO object, which if it is, it's a buffer of the image and not a real filename.

**Comment by victor-rene** [comment]
@matham, @akshayaurora, @kived
Is it possible to write a test suite for this? I mean, it seems there are many different cases for many different providers that must handled. Also it's important not to fail on this kind of thing. And there is still the gif issue. Would that be tests/test_zip_loader.py or a more general test for all 'sequenced_images' like in examples/widgets?

**Comment by akshayaurora** [comment]
what's the issue with gif? you guys don't have oil installed? is the native gif loader not working?

**Comment by akshayaurora** [comment]
@kived could you outline the issue with gif? if you set the KIVY_IMAGE=sdl2 or pygame or imageio gif's will fail as these loaders don't support gif. Is there a issue with the loaders that do support GIF loading?
