### ISSUE TITLE
Cython 0.22 does not compile master

### ISSUE THREAD

**Issue by matham** [kivy/kivy#2805]
Using cython dev from github:

```shell
e:\MinGW\bin\gcc.exe -shared -s build\temp.win32-2.7\Release\kivy\graphics\trans
formation.o build\temp.win32-2.7\Release\kivy\graphics\transformation.def -Le:\P
ython27\libs -Le:\Python27\PCbuild -lopengl32 -lglew32 -lpython27 -lmsvcr90 -o G
:\Python\dev2\kivy\kivy\graphics\transformation.pyd -lm
cythoning kivy\graphics/vbo.pyx to kivy\graphics\vbo.c

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cpdef release(self)
     cpdef get_pixel_color(self, int wx, int wy)

     cdef void create_fbo(self)
     cdef void delete_fbo(self)
     cdef void apply(self)
                   ^
 ------------------------------------------------------------

 kivy\graphics\fbo.pxd:27:19: Signature not compatible with previous declaration


 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef void push_states(self, list names) except *
     cdef void pop_state(self, str name) except *
     cdef void pop_states(self, list names) except *
     cdef void enter(self) except *
     cdef void leave(self) except *
     cdef void apply(self) except *
                   ^
 ------------------------------------------------------------

 kivy\graphics\instructions.pxd:123:19: Previous declaration is here
building 'kivy.graphics.vbo' extension
e:\MinGW\bin\gcc.exe -mdll -O -Wall -Ie:\Python27\include -Ie:\Python27\PC -c ki
vy\graphics\vbo.c -o build\temp.win32-2.7\Release\kivy\graphics\vbo.o
kivy\graphics\vbo.c:1:2: error: #error Do not use this file, it is the result of
 a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
 error: command 'e:\\MinGW\\bin\\gcc.exe' failed with exit status 1
make: *** [force] Error 1
```

I think they most have become stricter about keeping function prototypes consistent.

**Comment by matham** [comment]
Reopening because this is now a issue with cython 0.22 on pip.

**Comment by matham** [comment]
Here's the cython bug report of this issue: https://groups.google.com/forum/#!topic/cython-users/r3dQSfOKMjI

**Comment by kived** [comment]
@matham, adding `except *` works on Linux. Could you check if my PR works for you on Windows? If it doesn't, there might be something specific to Windows we can fix to make it work with 0.22.

**Comment by kived** [comment]
Closing because we now refuse to build, with a helpful error message, on Cython 0.22 (and 0.22.alpha0, 0.22.beta0).

**Comment by tleeuwenburg** [comment]
Unfortunately, this is still affecting the macports version, which tries to use the latest cython, which is 0.22_0. From a developer perspective, I get it, but from a user perspective this is a big pain. I've commented on the cython bug also. I think Kivy is an excluded option for me until this is fixed.

**Comment by donpdonp** [comment]
I ran into the cython 0.22 build problem on ubuntu 15.04. quick fix is 
```
$ pip install -I cython==0.21
```

**Comment by Kovak** [comment]
master should compile on cython .22 now, if you are using the last stable release you will need to use cython .21 I believe
