### ISSUE TITLE
Kivy with Python 3.5 (Ubuntu)

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#3751]
Is it possible to run kivy with python 3.5 on ubuntu?
It works with python 2.7. It also works with python 3.5 on windows.

	monny@aPC:~$ python3.5 helloWorld.py
	[INFO   ] [Logger      ] Record log in /home/monny/.kivy/logs/kivy_15-11-06_9.txt
	[INFO   ] [Kivy        ] v1.9.0
	[INFO   ] [Python      ] v3.5.0+ (default, Oct 11 2015, 09:05:38)
	[GCC 5.2.1 20151010]
	[INFO   ] [Factory     ] 173 symbols loaded
	[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
	[INFO   ] [Text        ] Provider: sdl2
	[INFO   ] [OSC         ] using <multiprocessing> for socket
	[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
	[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
	egl_rpi - ImportError: cannot import name 'bcm'
	  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib    fromlist=[modulename], level=0)
	  File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
		from kivy.lib.vidcore_lite import bcm, egl
	 
	sdl2 - TypeError: expected bytes, str found
	  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 65, in core_select_lib
		cls = cls()
	  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 121, in __init__
		super(WindowSDL, self).__init__()
	  File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 616, in __init__
		self.create_window()
	  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 171, in create_window
		self.fullscreen, resizable, state)
	  File "kivy/core/window/_window_sdl2.pyx", line 60, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1379)
	 
	x11 - ImportError: No module named 'kivy.core.window.window_x11'
	  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib
		fromlist=[modulename], level=0)
	 
	[CRITICAL] [App         ] Unable to get a Window, abort.
	 Exception ignored in: 'kivy.properties.dpi2px'
	 Traceback (most recent call last):
	   File "/usr/lib/python3/dist-packages/kivy/utils.py", line 360, in __get__
		 retval = self.func(inst)
	   File "/usr/lib/python3/dist-packages/kivy/metrics.py", line 169, in dpi
		 EventLoop.ensure_window()
	   File "/usr/lib/python3/dist-packages/kivy/base.py", line 126, in ensure_window
		 sys.exit(1)
	 SystemExit: 1
	[CRITICAL] [App         ] Unable to get a Window, abort.

helloWorld.py content:

	from kivy.app import App
	from kivy.uix.button import Button

	class TestApp(App):
		def build(self):
			return Button(text='Hello World')

	TestApp().run()

**Comment by CreamyCookie** [comment]
I can't run Kivy 1.9 with neither Python 3.4 nor 3.5. (Installed via `sudo apt-get install python3-kivy`)

>  ImportError: No module named 'kivy.uix.behaviors'

**Comment by dessant** [comment]
@CreamyCookie, have you also installed all these deps? http://kivy.org/docs/installation/installation-linux.html#ubuntu-example

**Comment by dessant** [comment]
Reinstall kivy after ensuring that they are present.

**Comment by CreamyCookie** [comment]
@dessant No, but I thought this wasn't necessary, because it's in the "Installation in a Virtual Environment" part, and I installed via `sudo apt-get install python3-kivy`.

But if I try to install these, this is what I get: (I'm on Ubuntu 15.10)

    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     libavcodec-dev : Depends: libavcodec-ffmpeg56 (= 7:2.7.2-1build1) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

**Comment by dessant** [comment]
@thopiekar pingly

**Comment by thopiekar** [comment]
Stable or daily PPA?

**Comment by thopiekar** [comment]
Can confirm this on daily PPA. Affects all python* versions. kivy.uix.behaviors seems to be a new module in kivy (sorry for not being up-to-date).
Will fix that shortly!

**Comment by thopiekar** [comment]
For those who are interested: The failing buildlog at launchpad says everything:

```
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/drag.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/togglebutton.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/drag.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/__init__.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/focus.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/__init__.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/codenavigation.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/focus.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/button.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/togglebutton.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/codenavigation.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/compoundselection.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/button.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python2.7/dist-packages/kivy/uix/behaviors/compoundselection.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/drag.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/togglebutton.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__init__.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/focus.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/button.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/codenavigation.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/compoundselection.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/compoundselection.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/focus.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/__init__.cpython-34.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/__init__.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/togglebutton.cpython-34.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/drag.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/codenavigation.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/codenavigation.cpython-34.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/drag.cpython-34.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/compoundselection.cpython-34.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/togglebutton.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/button.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/focus.cpython-34.pyc exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/kivy/uix/behaviors/__pycache__/button.cpython-34.pyc exists in debian/tmp but is not installed to anywhere
```

The only reason why we have packages not finding the uix.behaviours is that the changes, which use this new module were uploaded before adding uix.behaviours itself ^^

**Comment by CreamyCookie** [comment]
Stable.

>  Will fix that shortly!

Nice! And btw. thanks for your great work, kivy developers! :+1:

**Comment by inclement** [comment]
Was the original issue here ever addressed?

**Comment by dessant** [comment]
@inclement it was, closing.

**Comment by openourweb** [comment]
I still have the issue with python 3.5 in ubuntu 17.04:
(kivyinstall) john@john-P37V6:~$ python3 -c "import kivy"
[WARNING] [Config      ] Older configuration version detected (14 instead of 19)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/john/.kivy/logs/kivy_17-09-01_11.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.3 |Anaconda custom (64-bit)| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

errors:INFO   ] [Logger      ] Record log in /home/john/.kivy/logs/kivy_17-09-01_9.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.3 |Anaconda custom (64-bit)| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/john/anaconda3/lib/python3.5/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/john/anaconda3/lib/python3.5/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - ImportError: /home/john/anaconda3/lib/python3.5/site-packages/numexpr/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libmodplug.so.1)
  File "/home/john/anaconda3/lib/python3.5/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/john/anaconda3/lib/python3.5/site-packages/kivy/core/window/window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

x11 - ImportError: No module named 'kivy.core.window.window_x11'
  File "/home/john/anaconda3/lib/python3.5/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.

**Comment by IQYottabit** [comment]
I too still have this issue in python3.5 in Ubuntu 16.04. it works fine using python2.7

Error code: 

´´´
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - TypeError: expected bytes, str found
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 65, in core_select_lib
    cls = cls()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 121, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 616, in __init__
    self.create_window()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 171, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 60, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1447)

x11 - ImportError: No module named 'kivy.core.window.window_x11'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kivy/utils.py", line 360, in __get__
     retval = self.func(inst)
   File "/usr/lib/python3/dist-packages/kivy/metrics.py", line 169, in dpi
     EventLoop.ensure_window()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 126, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.

´´´

**Comment by dessant** [comment]
@IQYottabit, you're using an older version, try Kivy 1.10.0. If you are able to reproduce the bug with the latest release, open a new issue with the required details.

**Comment by IQYottabit** [comment]
Thanks, that solved the issue. I update the Kivy 1.10.0 now.
