### ISSUE TITLE
Cannot build basic example in Kivy Android VM

### ISSUE THREAD

**Issue by Godsmith** [kivy/kivy#4616]
I downloaded the https://kivy.org/docs/guide/packaging-android-vm.html#kivy-android-vm and tried to build the example code from https://kivy.org/docs/guide/basic.html. `buildozer android debug` fails with the exact same errors as specified in this thread: https://groups.google.com/forum/#!msg/kivy-users/WmD2saKskcg/TWxwqpOHBgAJ

I tried the solutions specified by Rob Heath in that thread, and each fix got me the further the exact same way as for him, but like him, I was also forced to give up at the "undefined reference to 'SDL_main'" error.

I tried again after updating buildozer in the VM to 0.32 by doing `sudo pip install -U buildozer`, and also updated Kivy etc by doing `rm -rf ~/.buildozer/android/packages` but got the exact same error messages afterwards.

**Comment by palak1309** [comment]
i still have the same issue any help?

**Comment by misl6** [comment]
Closing as the `Android VM` doesn't exist anymore.
When packaging Android Apps, please refer to: https://kivy.org/doc/stable/guide/packaging-android.html#buildozer
